const path = require('path');

if (!config.resolve) {
  config.resolve = {};
}

config.resolve.alias = {
  ...(config.resolve.alias || {}),
  'core-crypto-ffi_bg.wasm$': require.resolve('@wireapp/core-crypto/src/autogenerated/core-crypto-ffi_bg.wasm'),
  'fs/promises$': false,
};

config.resolve.fallback = {
  ...(config.resolve.fallback || {}),
  fs: false,
};

config.experiments = {
  ...(config.experiments || {}),
  asyncWebAssembly: true,
};

config.module = config.module || {};
config.module.rules = config.module.rules || [];
config.module.rules.push({
  test: /core-crypto-ffi_bg\.wasm$/,
  type: 'asset/resource',
});
